#!/bin/sh

home_route="$(curl https://trevordmiller.com)"
if [[ $home_route != *"My posts about software development."* ]]; then
  echo "ERROR: The home route is not working as expected!";
  exit 1;
fi

post_route="$(curl https://trevordmiller.com/programming-principles/)"
if [[ $post_route != *"My guiding principles for software development in general."* ]]; then
  echo "ERROR: A post route is not working as expected!";
  exit 1;
fi

about_route="$(curl https://trevordmiller.com/about/)"
if [[ $about_route != *"My personal background."* ]]; then
  echo "ERROR: The about route is not working as expected!";
  exit 1;
fi

resume_route="$(curl https://trevordmiller.com/resume/)"
if [[ $resume_route != *"My professional background."* ]]; then
  echo "ERROR: The resume route is not working as expected!";
  exit 1;
fi

projects_route="$(curl https://trevordmiller.com/projects/)"
if [[ $projects_route != *"My open source projects."* ]]; then
  echo "ERROR: The projects route is not working as expected!";
  exit 1;
fi

rss_route="$(curl -Is https://trevordmiller.com/rss.xml | head -n 1)"
if [[ $rss_route != *"200"* ]]; then
  echo "ERROR: The rss route is not working as expected!";
  exit 1;
fi
