#!/bin/sh

home_route="$(curl https://trevordmiller.com)"
if [[ $home_route != *"My resources I write to help me remember what I learn."* ]]; then
  echo "ERROR: The home route is not working as expected!";
  exit 1;
fi

writing_route="$(curl https://trevordmiller.com/cicd-reference/)"
if [[ $writing_route != *"My reference sheet for automation with CI/CD."* ]]; then
  echo "ERROR: A writing route is not working as expected!";
  exit 1;
fi

about_route="$(curl https://trevordmiller.com/about/)"
if [[ $about_route != *"My personal background."* ]]; then
  echo "ERROR: The about route is not working as expected!";
  exit 1;
fi

resume_route="$(curl https://trevordmiller.com/resume/)"
if [[ $resume_route != *"My professional background."* ]]; then
  echo "ERROR: The resume route is not working as expected!";
  exit 1;
fi

projects_route="$(curl https://trevordmiller.com/projects/)"
if [[ $projects_route != *"My open source projects."* ]]; then
  echo "ERROR: The projects route is not working as expected!";
  exit 1;
fi

rss_route="$(curl -Is https://trevordmiller.com/rss.xml | head -n 1)"
if [[ $rss_route != *"200"* ]]; then
  echo "ERROR: The rss route is not working as expected!";
  exit 1;
fi
