#!/bin/bash
set -euo pipefail


# ==================================================================
# DOTFILES
# ==================================================================

echo "Symlinking dotfiles"
for file in $(find "$HOME/settings/dotfiles" -depth 1 -exec basename {} \;); do
  ln -s "$HOME/settings/dotfiles/$file" "$HOME/$file"
done


# ==================================================================
# PACKAGES
# ==================================================================

# HOMEBREW

echo "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Installing and configuring Homebrew packages"

homebrew_packages=(
  "bash"
  "tmux"
  "reattach-to-user-namespace"
  "vim"
  "git"
  "node"
  "n"
)
for homebrew_package in "${homebrew_packages[@]}"; do
  brew install "$homebrew_package"
done

echo "Making bash the default shell"
chsh -s /bin/bash

echo "Installing Vim plugin manager"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    
echo "Installing Vim plugins"
vim +PlugInstall +qall

echo "Making Vim history file directories"
mkdir ~/.vim/{backup_files,swap_files,undo_files}

echo "Upgrading to latest Node"
n latest

echo "Adding npm user"
npm adduser

# RUBY

echo "Installing and configuring Ruby gems"

ruby_gems=(
  "travis"
)
for ruby_gem in "${ruby_gems[@]}"; do
  gem install "$ruby_gem"
done

echo "Adding Travis user"
travis login


# ==================================================================
# APPS & FONTS
# ==================================================================

echo "Installing Homebrew cask packages"

brew tap caskroom/fonts

homebrew_cask_packages=(
  "hyper"
  "google-chrome"
  "1password"
  "rescuetime"
  "kap"
  "sketch"
  "spotify"
  "font-fira-mono"
  "font-quicksand"
)
for homebrew_cask_package in "${homebrew_cask_packages[@]}"; do
  brew cask install "$homebrew_cask_package"
done


# ==================================================================
# MACOS
# ==================================================================

# KEYBOARD

echo "Configuring key repeat"
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# HIDDEN FILES

echo "Configuring hidden files to show"
defaults write com.apple.finder AppleShowAllFiles YES
killall Finder

# MENU BAR

echo "Configuring menu bar to autohide"
defaults write NSGlobalDomain _HIHideMenuBar -bool true
killall Finder

# DOCK

echo "Configuring dock to autohide"
osascript <<EOD
  tell application "System Events"
    if (get autohide of dock preferences) is false then
      tell dock preferences to set autohide to not autohide
    end if
  end tell
EOD

# SCREENSHOTS

echo "Configuring screenshots to save in Downloads"
defaults write com.apple.screencapture location ~/Downloads
killall SystemUIServer

# CHROME

echo "Configuring incognito mode"
defaults write com.google.chrome IncognitoModeAvailability -integer 1


# ==================================================================

echo "Done"
