#!/bin/bash
set -euo pipefail

# USAGE
# script-split 2 "echo 'hello world'"
# script-split [{pane_count}] [{pane_2_command}] [{pane_3_command}] etc
#   {pane_count} defaults to 3
#   {pane_2_command} defaults to "yarn start"
#   {pane_3_command} defaults to "yarn test"

tmux new-session -d 
split_count=${1:-3}
index=1
while [ "$index" -lt "$split_count" ]
do
  tmux split-window
  let "index+=1"
done

if [ $# -ge 2 ]; then
  index=1
  for command in "${@:2}"
  do
    tmux send-keys -t $index C-z $command Enter
    let "index+=1"
  done
else
  tmux send-keys -t 1 C-z "yarn start" Enter
  tmux send-keys -t 2 C-z "yarn test" Enter
fi

tmux set-window-option main-pane-height 30
tmux select-layout main-horizontal
tmux select-pane -t 0
tmux attach-session -d 
