#!/bin/bash
set -euo pipefail

script-log state "Upgrading Homebrew + brew/cask packages"
brew update && brew upgrade

script-log state "Upgrading Node"
n latest

script-log state "Upgrading npm + global npm packages"
npm update -g

script-log state "Upgrading Vim plugins"
vim +PluginInstall +PluginClean +qall

script-log state "Upgrading macOS"
sudo softwareupdate -ia

script-log state "Done"
