#!/usr/bin/env osascript

do shell script "script-log state 'Opening native apps'"
set nativeApps to {"Todoist", "/Applications/Hyper.app", "Google Chrome", "Calendar", "Spotify", "Messages", "Mail", "Slack"}
repeat with nativeApp in nativeApps
	run application nativeApp
end repeat

do shell script "script-log state 'Opening web apps'"
set webApps to {"https://docs.google.com/document/d/1O2Me9-4GoYfvEwrIXkyHDAJQs-P2eJXZ6YKJYqJhVWg"}
repeat with webApp in webApps
	do shell script "open " & webApp
end repeat

do shell script "script-windows"

tell application "/Applications/Hyper.app" to activate
do shell script "script-fullscreen"

do shell script "script-log state 'Opening dev tools'"
delay 3
tell application "Google Chrome" to activate
set devToolsTabs to {2}
repeat with devToolsTab in devToolsTabs
	tell application "Google Chrome" to set active tab index of first window to devToolsTab
	tell application "System Events"
		keystroke "i" using {command down, option down}
	end tell
end repeat

do shell script "script-log state 'Done'"
