#!/usr/bin/env osascript

do shell script "script-log state 'Reverting screen resolution'"
delay 3
tell application "SwitchResX Daemon"
	set current mode of display 1 to mode 1 of display 1
end tell

do shell script "script-donotdisturb-reset"

do shell script "script-demo-reset"

do shell script "script-log state 'Done'"
