#!/usr/bin/env osascript

do shell script "script-demo"

set nativeApps to {"Google Chrome", "SwitchResX Daemon", "ScreenFlow", "Todoist", "/Applications/Hyper.app"}
repeat with nativeApp in nativeApps
	run application nativeApp
end repeat

set webApps to {"https://github.com/trevordmiller?tab=repositories&q=example"}
repeat with webApp in webApps
	do shell script "open " & webApp
end repeat

delay 3
tell application "SwitchResX Daemon"
	set res to modes of display 1 whose (width = 1280 and height = 720 and definition = 2)
	set current mode of display 1 to first item of res
end tell

do shell script "script-windows"

tell application "/Applications/Hyper.app" to activate
do shell script "script-fullscreen"

do shell script "cd $HOME/drive/personal/eggheadio"

do shell script "script-donotdisturb"

return "Done"
