#!/bin/bash
set -euo pipefail

task="Setting up for screencasting"

script-log state "$task"

script-demo

script-donotdisturb

items=(
  "/Applications/Google Chrome.app"
  "/Applications/SwitchResX.app"
  "/Applications/ScreenFlow.app"
  "/Applications/Todoist.app"
  "/Applications/Hyper.app"
  "https://github.com/trevordmiller?tab=repositories&q=example"
)
for item in "${items[@]}"; do
  open "$item"
done

sleep 3
osascript <<EOD
  tell application "SwitchResX Daemon"
    set res to modes of display 1 whose (width = 1280 and height = 720 and definition = 2)
    set current mode of display 1 to first item of res
  end tell
EOD

script-windows

open "/Applications/Hyper.app"
script-fullscreen

cd "$HOME"/drive/personal/eggheadio

script-log state "DONE $task"
