#!/bin/bash
set -euo pipefail

script-log state "Reverting terminal and editor settings to normal"

cd "$HOME"/drive/settings/dotfiles
git checkout .hyper.js .vimrc

sleep 3
clear

script-log state "Done"
