#!/usr/bin/env osascript

delay 3
tell application "SwitchResX Daemon"
	set current mode of display 1 to mode 1 of display 1
end tell

do shell script "script-donotdisturb-reset"

do shell script "script-demo-reset"

return "Done"
