#!/bin/bash
set -euo pipefail

tmux new-session -d
split_count=${1:-3}
index=1
while [ "$index" -lt "$split_count" ]
do
  tmux split-window
  let "index+=1"
done
tmux set-window-option main-pane-height 30
tmux select-layout main-horizontal
tmux select-pane -t 0
tmux attach-session -d 
