#!/bin/bash
set -euo pipefail

script-log state "Loading terminal and editor demo settings"

sed -i "" -e "s/fontSize: 17/fontSize: 30/" -e "s/nova-hyperterm/hyperterm-one-light/" "$HOME/drive/settings/dotfiles/.hyper.js"

vimrcRules=(
  "set laststatus=0"
  "set noshowmode"
  "set background=light"
  "colorscheme one"
)
for vimrcRule in "${vimrcRules[@]}"; do
  echo "$vimrcRule" >> "$HOME/drive/settings/dotfiles/.vimrc"
done

sleep 3
clear

script-log state "Done"
