#!/bin/bash
set -euo pipefail

script-log state "Upgrading Homebrew + brew packages"
brew update
brew upgrade

script-log state "Upgrading Node"
n latest

script-log state "Upgrading global yarn packages"
yarn global upgrade

script-log state "Upgrading Vim plugins"
vim +PluginInstall +PluginClean +qall

script-log state "Upgrading Mac App Store apps"
mas upgrade

script-log state "Upgrading macOS"
sudo softwareupdate -ia

script-log state "Done"
