#!/bin/bash
set -euo pipefail

task="Setting up for work"

script-log state "$task"

items=(
  "/Applications/Todoist.app"
  "/Applications/Hyper.app"
  "/Applications/Google Chrome.app"
  "/Applications/Calendar.app"
  "/Applications/Spotify.app"
  "/Applications/Messages.app"
  "/Applications/Mail.app"
  "/Applications/Slack.app"
  "https://docs.google.com/document/d/1O2Me9-4GoYfvEwrIXkyHDAJQs-P2eJXZ6YKJYqJhVWg"
  "http://localhost:2000/"
  "http://localhost:3000"
)
for item in "${items[@]}"; do
  open "$item"
done

script-windows

sleep 3

open "/Applications/Google Chrome.app"
osascript <<EOD
  set devToolsTabs to {3}
  repeat with devToolsTab in devToolsTabs
    tell application "Google Chrome" to set active tab index of first window to devToolsTab
    tell application "System Events"
      keystroke "i" using {command down, option down}
    end tell
  end repeat
EOD

sleep 3

open "/Applications/Hyper.app"
osascript <<EOD
  do shell script "script-fullscreen"
  tell application "System Events"
    keystroke "t" using {command down}
    delay 1
    keystroke "cd \"$HOME\"/drive/work/egghead-instructor-center && script-split"
  end tell
EOD

sleep 3

script-log state "DONE $task"
