#!/bin/bash
set -euo pipefail

task="Managing windows"

script-log state "$task"

sleep 3
osascript <<EOD
  tell application "System Events"
    key code 18 using {command down, option down, control down}
  end tell
EOD

script-log state "DONE $task"
