#!/bin/bash
set -euo pipefail

task="Cleaning folders"

script-log state "$task"

brew cleanup
brew cask cleanup
find "$HOME"/drive -name 'node_modules' -type d -exec rm -r '{}' ';' || true
rm -rf "$HOME"/drive/personal/playground/*
rm -rf "$HOME"/Downloads/*

script-log state "DONE $task"
