#!/bin/bash
set -euo pipefail

script-log state "Checking if any git repos are dirty"
cd "$HOME"/drive
output=$(script-status | grep \
-e "Untracked files:" \
-e "Changes not staged for commit:"  \
-e "Changes to be committed:" \
)
if [ -z "$output" ]
then 
  script-log state "All git repos are clean";
  exit 0;
else
  script-log action "Clean dirty git repos!";
  script-status
  exit 1;
fi
script-log state "Done";
