#!/bin/bash
set -euo pipefail

task="Turning on Do Not Disturb"

script-log state "$task"

sleep 3
osascript <<EOD
  tell application "System Events"
    tell application process "SystemUIServer"
      try
        key down option
        click menu bar item "Notification Center" of menu bar 2
        key up option
      on error
        key up option
      end try
    end tell
  end tell
EOD

script-log state "DONE $task"
