#!/bin/bash
set -euo pipefail

task="Killing processes"

script-log state "$task"

killall node || true
killall phantomjs || true
tmux kill-server || true
cd ~/drive/work/egghead-systems
vagrant halt

script-log state "DONE $task"
