#!/usr/bin/env osascript

do shell script "script-log state 'Turning on Do Not Disturb'"
delay 3
tell application "System Events"
	tell application process "SystemUIServer"
		try
			key down option
			click menu bar item "Notification Center" of menu bar 2
			key up option
		on error
			key up option
		end try
	end tell
end tell
do shell script "script-log state 'Done'"
