#!/bin/bash
set -euo pipefail

script-log state "Checking if any git repos are dirty"
cd "$HOME"/drive
output=$(script-status | grep \
-e "Untracked files:" \
-e "Changes not staged for commit:"  \
-e "Changes to be committed:" \
-e "Your branch is ahead" \
)
if [ -z "$output" ]
then 
  script-log state "All git repos are clean";
else
  script-log action "TODO: Clean dirty git repos!";
  script-status
fi
script-log state "Done";
