#!/bin/bash
set -euo pipefail

task="Killing processes"

script-log state "$task"

killall node || true
tmux kill-server || true
brew services stop postgresql || true
redis-cli shutdown || true

script-log state "DONE $task"
