#!/bin/bash
set -euo pipefail

task="Generating a project"

script-log state "$task"

# VARIABLES
template_path=$HOME/drive/settings/scripts/script-project/
user_name="trevordmiller"
user_full_name="Trevor D. Miller"
user_website="https://trevordmiller.com"
project_year=$(date +"%Y")
project_type=$1
project_name=$2
project_description=$3

# ROOT DIRECTORY
mkdir "$project_name"
cd "$project_name"

# INITIAL FILES/DEPENDENCIES
cp -a "$template_path"/shared/. ./
case "$project_type" in 
  "library" ) 
    cp -a "$template_path"/library/. ./
    ;; 
  "web-app" ) 
    cp -a "$template_path"/web-app/. ./
    ;; 
  "service" ) 
    cp -a "$template_path"/service/. ./
    ;; 
esac

# INSTANCE SUBSTITUTION
grep -rl '%substitute' . --exclude-dir=node_modules | xargs sed -i '' \
-e "s|%substitute_user_name|$user_name|g" \
-e "s|%substitute_user_full_name|$user_full_name|g" \
-e "s|%substitute_user_website|$user_website|g" \
-e "s|%substitute_project_year|$project_year|g" \
-e "s|%substitute_project_name|$project_name|g" \
-e "s|%substitute_project_description|$project_description|g" 

# DEPENDENCIES
touch yarn.lock
yarn add --dev eslint jest
case "$project_type" in 
  "library" ) 
    yarn add --dev babel-cli babel-preset-env
    ;; 
  "web-app" ) 
    yarn add --dev eslint-plugin-react now
    yarn add react react-dom next
    ;; 
  "service" ) 
    yarn add --dev node-fetch now
    yarn add micro
    ;; 
esac

# SOURCE CONTROL
git init
git add -A
git commit -m "Scaffold project"
script-log action "Enter GitHub 2fa password"
curl -u "$user_name" https://api.github.com/user/repos -d "{\"name\":\"$project_name\", \"description\":\"$project_description\"}"
sleep 3
git remote add origin https://github.com/"$user_name"/"$project_name".git
git push -u origin master
open "https://github.com/$user_name/$project_name"

# CONTINUOUS INTEGRATION
travis enable -r "$user_name"/"$project_name"
open "https://travis-ci.org/$user_name/$project_name"

# RELEASE
yarn release
case "$project_type" in 
  "library" ) 
    open "https://www.npmjs.com/package/$project_name"
    ;; 
  "web-app" )
    open "$(pbpaste)"
    ;;
  "service" )
    open "$(pbpaste)"
    ;;
esac

script-log state "DONE $task"
