#!/bin/bash
set -euo pipefail

script-log state "Pulling latest"
git pull

script-log state "Bumping version"
yarn version

script-log state "Pushing"
git push --set-upstream origin master
git push --tags

script-log state "Done"
