#!/bin/bash
set -euo pipefail

user_name="trevordmiller"
current_repo_path=$(git rev-parse --show-toplevel)
current_repo=$(basename "$current_repo_path")
current_branch=$(git rev-parse --abbrev-ref HEAD)
release_type=$1

script-log state "Pulling latest"
git pull

script-log state "Switching to release branch"
git branch -d release
git checkout -b release

script-log state "Bumping version"
npm version "$release_type"
git add -A
git commit -m "Release"

script-log state "Pushing"
git push && git push --tags

script-log action "Submit pull request"
open https://github.com/"$user_name"/"$current_repo"/compare/master..."$current_branch"?expand=1

script-log state "Done"
