#!/bin/bash
set -euo pipefail


# ==================================================================
# APPS
# ==================================================================

apps=(
  "Todoist"
  "Messages"
  "Calendar"
  "Mail"
  "Photos"
  "Day One"
  "Anki"
)

for app in "${apps[@]}"; do
  open -a "$app"
done


# ==================================================================
# WEBSITES
# ==================================================================

websites=(
  "https://app.youneedabudget.com"
  "https://feedly.com"
  "https://app.meetedgar.com/upcoming_posts"
  "https://www.facebook.com"
)

open -a "Google Chrome" --args --profile-directory="Profile 3"
for website in "${websites[@]}"; do
  open "$website"
done
