#!/bin/bash
set -euo pipefail

cd ~
tmux-window "cortex-api" "repos/cortex-api" 3 "npm run dev" "npm test:watch"
tmux-window "cortex-components" "repos/cortex-components" 3 "npm run dev" "npm run test:watch"
tmux-window "cortex-clients" "repos/cortex-clients" 3 "npm run dev" "npm test"
