#!/bin/bash
set -euo pipefail

# ==================================================================
# APPS
# ==================================================================

apps=(
	"Todoist"
	"iTerm"
	"Slack"
	"Trello"
	"Calendar"
	"Mail"
	"Spotify"
)

for app in "${apps[@]}"; do
	open -a "$app"
done

# ==================================================================
# TERMINAL WORKFLOW
# ==================================================================

DEFAULT_DIRECTORY="$HOME/repos/edgar"
cd "$DEFAULT_DIRECTORY"
tmux new-session -d -s "edgar"
tmux rename-window "background"
tmux send-keys -t 0 C-z "foreman start -f Procfile.dev" Enter
tmux new-window -c "$DEFAULT_DIRECTORY"
tmux rename-window "shell"
tmux send-keys -t 0 C-z "git status" Enter
tmux new-window -c "$DEFAULT_DIRECTORY"
tmux rename-window "main"
tmux send-keys -t 0 C-z "vim -c 'E'" Enter
tmux attach-session -d
