#!/bin/bash
set -euo pipefail

echo "Closing apps"

foreground_apps_string=$(osascript -e 'tell application "System Events" to get name of (processes where background only is false)')

IFS=',' read -r -a foreground_apps <<<"$foreground_apps_string"

for foreground_app in "${foreground_apps[@]}"; do
	app_name=$(echo "$foreground_app" | sed 's/^ *//g')
	if [[ ! "$app_name" == "Finder" && ! "$app_name" == "alacritty" ]]; then
		osascript -e 'quit app "'"$app_name"'"'
	fi
done

echo "Pulling latest dotfiles and shell scripts"

cd "$HOME/repos/dotfiles"
git pull

cd "$HOME/repos/shell-scripts"
git pull

echo "Making sure Brewfile and machine installs are in sync"

cd ~

brew_bundle_cleanup_output=$(brew bundle cleanup)

if [ -z "$brew_bundle_cleanup_output" ]; then
	echo "Brewfile and machine installs are in sync"
else
	echo "Inconsistencies were found between Brewfile and machine installs. Fix them and re-run."
	brew bundle cleanup
	exit 1
fi

echo "Removing homebrew artifacts"

brew cleanup

echo "Removing OS artifacts"

find "$HOME/repos" -name '.DS_Store' -delete

echo "Removing downloads"

rm -rf "$HOME"/Downloads/*

echo "Removing merged local branches in each git repo"

deep_git_prune() {
	IFS=$'\n\t'

	set +e
	LOCAL_BRANCHES=$(git branch --merged master | grep -v -e 'master' -e '\*' | tr -d ' ')
	set -e

	if [[ -n "$LOCAL_BRANCHES" ]]; then
		for BRANCH in $LOCAL_BRANCHES; do
			git branch -d "$BRANCH"
		done
	fi
}

cd "$HOME/repos"
for i in */.git; do (
	echo $i
	cd $i/..
	deep_git_prune
); done

echo "Checking the status of each git repo"

deep_git_status() {
	cd "$HOME/repos"
	find . -path "*/.git" -maxdepth 2 -print -execdir git status ";"
}

deep_git_status_output=$(
	deep_git_status | grep \
		-e "Untracked files:" \
		-e "Changes not staged for commit:" \
		-e "Changes to be committed:" \
		-e "Your branch is ahead"
)

if [ -z "$deep_git_status_output" ]; then
	echo "All git repos are clean"
else
	echo "Dirty git repos were found! Fix them and re-run."
	deep_git_status
	exit 1
fi

echo "Quitting JavaScript processes"

killall node || true
