#!/bin/bash
set -euo pipefail

# ==================================================================
# APPS
# ==================================================================

apps=(
	"Anki"
)

for app in "${apps[@]}"; do
	open -a "$app"
done

# ==================================================================
# WEBSITES
# ==================================================================

websites=(
	"https://feedly.com"
	"https://feedly.com/i/saved"
)

open -a "Google Chrome" --args --profile-directory="Profile 3"
for website in "${websites[@]}"; do
	open "$website"
done
