#!/bin/bash
set -euo pipefail


# ==================================================================
# TERMINAL WORKFLOW
# ==================================================================

DEFAULT_DIRECTORY="$HOME/repos/nova-vim"
cd "$DEFAULT_DIRECTORY"
tmux new-session -d -s "nova-vim"
tmux rename-window "background"
tmux send-keys -t 0 C-z "npm run dev" Enter
tmux new-window -c "$DEFAULT_DIRECTORY"
tmux rename-window "shell"
tmux send-keys -t 0 C-z "git status" Enter
tmux new-window -c "$DEFAULT_DIRECTORY"
tmux rename-window "main"
tmux send-keys -t 0 C-z "vim -c 'E'" Enter
tmux attach-session -d
