#!/bin/bash
set -euo pipefail


# ==================================================================
# TERMINAL WORKFLOW
# ==================================================================

cd ~
DEFAULT_DIRECTORY="repos/nova-vim"

tmux new-window -c "$DEFAULT_DIRECTORY"
tmux rename-window "background"
tmux send-keys -t 0 C-z "npm run dev" Enter

tmux new-window -c "$DEFAULT_DIRECTORY"
tmux rename-window "main"
tmux send-keys -t 0 C-z "vim -c 'E'" Enter
