#!/bin/bash
set -euo pipefail

tmux new-session -d -s "$(basename $(pwd))"

tmux rename-window "background"
tmux splitw
tmux splitw

tmux new-window
tmux rename-window "main"
tmux send-keys -t 0 C-z "clear && git status" Enter

tmux new-window
tmux rename-window "editor"
tmux send-keys -t 0 C-z "vim -c 'E'" Enter

tmux attach-session -d
