#!/bin/bash
set -euo pipefail

# ==================================================================
# APPS
# ==================================================================

apps=(
	"System Preferences"
	"QuickTime Player"
)

for app in "${apps[@]}"; do
	open -a "$app"
done
