#!/bin/bash
set -euo pipefail

cd ~/drive/work/egghead-rails
script-split 3 "bundle install && yarn install && foreman start -f Procfile.dev" "brew services start postgresql && redis-server /usr/local/etc/redis.conf"
