#!/usr/bin/env osascript

on getTodayApps(core, other, work, background)
	set today to weekday of (current date)
	if (today = Sunday) then
		return core & background
	else if (today = Saturday) then
		return core & other & background
	else
		return core & other & work & background
	end if
end getTodayApps

set core to {"Todoist", "Calendar", "Messages", "Mail"}
set other to {"Photos", "Anki", "Spotify", "Slack"}
set work to {}
set background to {"Google Drive", "Google Photos Backup", "Flux", "Slate", "Seil", "Karabiner"}
set nativeApps to getTodayApps(core, other, work, background)
repeat with nativeApp in nativeApps
	run application nativeApp
end repeat

set core to {"http://www.apple.com/ios/health", "https://myfitnesspal.com"}
set other to {"https://www.rescuetime.com/dashboard", "https://wakatime.com/dashboard", "https://www.mint.com", "https://www.egghead.io", "https://www.codewars.com", "https://buffer.com", "https://www.youtube.com/feed/subscriptions", "https://facebook.com", "https://twitter.com"}
set work to {"https://domo.demo.domo.com/inbox", "https://domo.domo.com/inbox", "https://domo.okta.com/home/jira_onprem/0oa1moe1d0joaWP4P0x7/3549", "https://git.empdev.domo.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+label%3A%22mobile-web%22", "https://app.getsentry.com/domo-mobile-web/mobileweb"}
set background to {}
set webApps to getTodayApps(core, other, work, background)
repeat with webApp in webApps
	do shell script "open " & webApp
end repeat

do shell script "script-ethernet"
do shell script "script-windows"
