#!/bin/bash
set -euo pipefail

task="Starting workflow based on day/time"

script-log state "$task"

work_workflow () { 
  echo 'Opening work workflow items'
  open "/Applications/Todoist.app"
  open "/Applications/Hyper.app"
  script-fullscreen
  open "/Applications/Spotify.app"
  open -a "/Applications/Google Chrome.app" --args --profile-directory="Profile 1"
} 

personal_workflow () { 
  echo 'Opening personal workflow items'
  open "/Applications/Todoist.app"
  open "/Applications/Hyper.app"
  script-fullscreen
  open "/Applications/Spotify.app"
  open -a "/Applications/Google Chrome.app" --args --profile-directory="Default"
}

if [[ $(date +%u) -lt 6 ]] ; then
  HOUR=$(date +%H)
  if (( 9 <= 10#$HOUR && 10#$HOUR < 17 )); then 
    work_workflow
  else
    personal_workflow
  fi
else
  personal_workflow
fi

script-log state "DONE $task"
