#!/bin/bash
set -euo pipefail

task="Opening apps and websites to check"

script-log state "$task"

items=(
  "https://www.icloud.com/#calendar"
  "/Applications/Messages.app"
  "https://www.icloud.com/#mail"
  "https://eggheadio.slack.com"
  "https://mail.google.com/mail/u/1/#inbox"
)
for item in "${items[@]}"; do
  open "$item"
done

say "Drink water, check posture, check apps and websites"

script-log state "DONE $task"
