#!/usr/bin/env osascript

set nativeApps to {"Flux"}
repeat with nativeApp in nativeApps
	run application nativeApp
end repeat

delay 1
tell application "SwitchResX Daemon"
	set current mode of display 1 to mode 1 of display 1
end tell

do shell script "script-donotdisturb-reset"

do shell script "ln -sf $HOME/Google\\ Drive/settings/dotfiles/.hyperterm.js $HOME/.hyperterm.js"

set nativeApps to {"Google Chrome", "SwitchResX Daemon", "ScreenFlow", "Todoist", "/Applications/HyperTerm.app"}
repeat with nativeApp in nativeApps
	tell application nativeApp to quit
end repeat
