#!/usr/bin/env osascript

delay 3
tell application "System Events"
	tell application process "SystemUIServer"
		try
			key down option
			click menu bar item "Notification Center" of menu bar 2
			key up option
		on error
			key up option
		end try
	end tell
end tell
