#!/bin/bash
set -euo pipefail

task="Opening apps and websites to check"

script-log state "$task"

items=(
  "https://todoist.com"
  "https://www.icloud.com/#calendar"
  "https://calendar.google.com/calendar/b/1/render?pli=1"
  "https://www.icloud.com/#mail"
  "https://mail.google.com/mail/u/1"
  "http://roederstudios.slack.com/"
  "https://utahjavascript.slack.com"
  "/Applications/Messages.app"
)
for item in "${items[@]}"; do
  open "$item"
done

script-log state "DONE $task"
