#!/bin/bash
set -euo pipefail

cd ~
tmux new-session -d -s playground
script-tmux-window "playground" "drive/personal/open-source/playground"
tmux kill-window -t 0
tmux select-window -t 1
tmux attach-session -d 
