#!/bin/bash
set -euo pipefail

task="Starting work workflow"

script-log state "$task"

open "/Applications/Todoist.app"
open "/Applications/Hyper.app"
script-fullscreen
open "/Applications/Slack.app"
open "/Applications/Spotify.app"
open -a "/Applications/Google Chrome.app" --args --profile-directory="Profile 1"
open "https://trello.com/b/55pvbyFV/snout-dev"
open "http://localhost:4000"
  
script-log state "DONE $task"
