#!/bin/bash
set -euo pipefail

# USAGE
# script-split 2 "echo 'hello world'"
# script-split [{pane_count}] [{pane_2_command}] [{pane_3_command}] etc
#   {pane_count} defaults to 3
#   pane 1 doesn't have a command as it is the main workspace up top
#   panes 2+ are secondary background tasks at the bottom
#   {pane_2_command} defaults to "yarn dev"
#   {pane_3_command} defaults to "yarn test"

task="Splitting terminal"

script-log state "$task"

tmux new-session -d 
split_count=${1:-2}
index=1
while [ "$index" -lt "$split_count" ]
do
  tmux split-window
  let "index+=1"
done

if [ $# -ge 2 ]; then
  index=1
  for command in "${@:2}"
  do
    tmux send-keys -t $index C-z "$command" Enter
    let "index+=1"
  done
else
  tmux send-keys -t 1 C-z "clear" Enter
fi

tmux set-window-option main-pane-height 30
tmux select-layout main-horizontal
tmux select-pane -t 0
tmux attach-session -d 

script-log state "DONE $task"
