#!/usr/bin/env osascript

set nativeApps to {"Todoist", "/Applications/HyperTerm.app", "Google Chrome", "Calendar", "Spotify", "Messages", "Mail", "Dash"}
repeat with nativeApp in nativeApps
	run application nativeApp
end repeat

set webApps to {"https://domo.demo.domo.com", "https://domo.okta.com/home/jira_onprem/0oa1moe1d0joaWP4P0x7/3549", "http://localhost:3000"}
repeat with webApp in webApps
	do shell script "open " & webApp
end repeat

do shell script "script-windows"

tell application "/Applications/HyperTerm.app" to activate
do shell script "script-fullscreen"

delay 1
tell application "Google Chrome" to activate
set devToolsTabs to {1, 3}
repeat with devToolsTab in devToolsTabs
	tell application "Google Chrome" to set active tab index of first window to devToolsTab
	tell application "System Events"
		keystroke "i" using {command down, option down}
	end tell
end repeat
