#!/bin/bash
set -euo pipefail

# USAGE
# script-project library hello-world "A CLI to say Hello World"
# script-project {project_type} {name} {description}
#  {project_type} can be library, web-app, or native-mobile-app
#  {name} should be a slug like hello-world
#  {description} should be a short sentence like "A server to say Hello World"

task="Generating a project"

script-log state "$task"

# VARIABLES
template_path=$HOME/drive/settings/scripts/utils/projects/
user_name="trevordmiller"
user_full_name="Trevor D. Miller"
user_website="https://trevordmiller.com"
project_year=$(date +"%Y")
project_type=$1
project_name=$2
project_description=$3

# ROOT DIRECTORY
mkdir "$project_name"
cd "$project_name"

# PROJECT TYPE SPECIFIC FILES/DEPENDENCIES
case "$project_type" in 
  "library" ) 
    cp -a "$template_path"/library/. ./
    yarn add --dev babel-cli babel-preset-env
    ;; 
  "web-app" ) 
    cp -a "$template_path"/web-app/. ./
    yarn add --dev eslint-plugin-react now
    yarn add react react-dom next
    ;; 
esac

# SHARED FILES/DEPENDENCIES
cp -a "$template_path"/shared/. ./
yarn add --dev eslint jest

# VARIABLE SUBSTITUTION
grep -rl '%substitute' . --exclude-dir=node_modules | xargs sed -i '' \
-e "s|%substitute_user_name|$user_name|g" \
-e "s|%substitute_user_full_name|$user_full_name|g" \
-e "s|%substitute_user_website|$user_website|g" \
-e "s|%substitute_project_year|$project_year|g" \
-e "s|%substitute_project_name|$project_name|g" \
-e "s|%substitute_project_description|$project_description|g" 

# SOURCE CONTROL
git init
git add -A
git commit -m "Scaffold project"
script-log action "Enter GitHub password"
curl -u "$user_name" https://api.github.com/user/repos -d "{\"name\":\"$project_name\", \"description\":\"$project_description\"}"
sleep 3
git remote add origin https://github.com/"$user_name"/"$project_name".git
git push -u origin master
open "https://github.com/$user_name/$project_name"

# CONTINUOUS INTEGRATION
travis enable -r "$user_name"/"$project_name"
open "https://travis-ci.org/$user_name/$project_name"

# RELEASE
case "$project_type" in 
  "library" ) 
    yarn publish
    open "https://www.npmjs.com/package/$project_name"
    ;; 
  "web-app" )
    now
    open "$(pbpaste)"
    ;;
esac

script-log state "DONE $task"
