#!/bin/bash
set -euo pipefail

task="Checking if any git repos are dirty"

script-log state "$task"

cd "$HOME"
output=$(script-git-statuses | grep \
-e "Untracked files:" \
-e "Changes not staged for commit:"  \
-e "Changes to be committed:" \
-e "Your branch is ahead" \
)

if [ -z "$output" ]
then 
  script-log state "All git repos are clean"
else
  script-log action "TODO: Clean dirty git repos!"
  script-git-statuses
fi

script-log state "DONE $task"
