#!/usr/bin/env osascript

set nativeApps to {"Flux"}
repeat with nativeApp in nativeApps
	tell application nativeApp to quit
end repeat

do shell script "ln -sf $HOME/drive/settings/dotfiles/.hyperterm.demo.js $HOME/.hyperterm.js"

set nativeApps to {"Google Chrome", "SwitchResX Daemon", "ScreenFlow", "Todoist", "/Applications/HyperTerm.app"}
repeat with nativeApp in nativeApps
	run application nativeApp
end repeat

set webApps to {"https://github.com/trevordmiller?tab=repositories&q=example"}
repeat with webApp in webApps
	do shell script "open " & webApp
end repeat

delay 1
tell application "SwitchResX Daemon"
	set res to modes of display 1 whose (width = 1280 and height = 720 and definition = 2)
	set current mode of display 1 to first item of res
end tell

do shell script "script-windows"

tell application "/Applications/HyperTerm.app" to activate
do shell script "script-fullscreen"

do shell script "cd $HOME/drive/personal/eggheadio"

do shell script "vim -c 'set background=light' -c 'colorscheme one' -c 'set laststatus=0' 'set noshowmode'"

do shell script "script-donotdisturb"
