#!/bin/bash
set -euo pipefail

task="Making active app fullscreen"

script-log state "$task"

sleep 3
osascript <<EOD
  tell application "System Events"
    keystroke "f" using {command down, control down}
  end tell
EOD

script-log state "DONE $task"
