#!/bin/bash
set -euo pipefail

task="Upgrading software"

script-log state "$task"

script-log state "Upgrading Homebrew + brew packages"
brew update
brew upgrade

script-log state "Upgrading Node"
sudo n latest

script-log state "Upgrading npm"
npm install npm@latest -g

script-log state "Upgrading Vim plugins"
vim +PlugUpgrade +PlugUpdate +PlugClean +qall

script-log state "Upgrading Mac App Store apps"
mas upgrade

script-log state "Upgrading macOS"
sudo softwareupdate -ia

script-log state "DONE $task"
