#!/bin/bash
set -euo pipefail

task="Killing processes"

script-log state "$task"

# NODE SERVERS
killall node || true

# TMUX SERVERS
tmux kill-server || true

# POSTGRES SERVERS
pkill postgres || true

script-log state "DONE $task"
