#!/bin/bash
set -euo pipefail

script-quit

task="Opening apps and websites to micro check"

script-log state "$task"

items=(
  "/Applications/Calendar.app"
  "/Applications/Messages.app"
  "/Applications/Mail.app"
  "/Applications/Slack.app"
)
for item in "${items[@]}"; do
  open "$item"
done

script-log state "DONE $task"
