#!/bin/bash
set -euo pipefail

echo "Creating ~/repos directory"
cd ~
mkdir repos

echo "Cloning shell scripts"
cd ~/repos
git clone https://github.com/trevordmiller/shell-scripts.git
cd ~

echo "Cloning dotfiles"
cd ~/repos
git clone https://github.com/trevordmiller/dotfiles.git
cd dotfiles
./index
cd ~

echo "Cloning practice problems"
cd ~/repos
git clone https://github.com/trevordmiller/practice-problems.git
cd ~

echo "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Installing global Homebrew packages"
brew bundle

echo "Installing Vim plugin manager"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing Vim plugins"
vim +PlugInstall +qall

echo "Creating Vim history file directories"
mkdir ~/.vim/{backup_files,swap_files,undo_files}

echo "Installing Node"
source ~/.bash_profile
nvm install --lts
nvm use --lts

echo "Adding npm user"
npm adduser

echo "Configuring keyboard key repeat"
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

echo "Configuring hidden files to show"
defaults write com.apple.finder AppleShowAllFiles YES
killall Finder

echo "Configuring menu bar to autohide"
defaults write NSGlobalDomain _HIHideMenuBar -bool true
killall Finder

echo "Configuring dock to autohide"
osascript <<EOD
  tell application "System Events"
    if (get autohide of dock preferences) is false then
      tell dock preferences to set autohide to not autohide
    end if
  end tell
EOD
echo "Configuring screenshots to save in Downloads"
defaults write com.apple.screencapture location ~/Downloads
killall SystemUIServer

echo "Configuring highest quality bluetooth audio"
sudo defaults write bluetoothaudiod "Enable AAC codec" -bool true

echo "Rebooting"
sudo shutdown -r now
