#!/bin/bash
set -euo pipefail


# ==================================================================
# ROOT
# ==================================================================

cd ~
mkdir repos
cd repos


# ==================================================================
# SHELL SCRIPTS
# ==================================================================

git clone https://github.com/trevordmiller/shell-scripts.git


# ==================================================================
# DOTFILES
# ==================================================================

git clone https://github.com/trevordmiller/dotfiles.git
cd dotfiles
./index


# ==================================================================
# PACKAGES
# ==================================================================

cd ~

# HOMEBREW

echo "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Installing and configuring Homebrew packages"

homebrew_packages=(
  "bash"
  "tmux"
  "reattach-to-user-namespace"
  "vim"
  "git"
  "node"
  "n"
  "mas"
)
for homebrew_package in "${homebrew_packages[@]}"; do
  brew install "$homebrew_package"
done

echo "Making bash the default shell"
chsh -s /bin/bash

echo "Installing Vim plugin manager"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    
echo "Installing Vim plugins"
vim +PlugInstall +qall

echo "Making Vim history file directories"
mkdir ~/.vim/{backup_files,swap_files,undo_files}

echo "Upgrading to latest Node"
n latest

echo "Adding npm user"
npm adduser

# RUBY

echo "Installing and configuring Ruby gems"

ruby_gems=(
  "travis"
)
for ruby_gem in "${ruby_gems[@]}"; do
  gem install "$ruby_gem"
done

echo "Adding Travis user"
travis login


# ==================================================================
# APPS & FONTS
# ==================================================================

echo "Installing Homebrew cask packages"

brew tap caskroom/fonts

homebrew_cask_packages=(
  "google-chrome"
  "iterm2"
  "1password"
  "anki"
  "rescuetime"
  "switchresx"
  "screenflow"
  "zoomus"
  "screenhero"
  "java"
  "google-cloud-sdk"
  "font-fira-mono"
)
for homebrew_cask_package in "${homebrew_cask_packages[@]}"; do
  brew cask install "$homebrew_cask_package"
done

echo "Installing Mac App Store apps"

mac_app_store_apps=(
  "585829637" # Todoist
  "1055511498" # Day One
)
for mac_app_store_app in "${mac_app_store_apps[@]}"; do
  mas install "$mac_app_store_app"
done


# ==================================================================
# MACOS
# ==================================================================

# KEYBOARD

echo "Configuring key repeat"
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# HIDDEN FILES

echo "Configuring hidden files to show"
defaults write com.apple.finder AppleShowAllFiles YES
killall Finder

# MENU BAR

echo "Configuring menu bar to autohide"
defaults write NSGlobalDomain _HIHideMenuBar -bool true
killall Finder

# DOCK

echo "Configuring dock to autohide"
osascript <<EOD
  tell application "System Events"
    if (get autohide of dock preferences) is false then
      tell dock preferences to set autohide to not autohide
    end if
  end tell
EOD

# SCREENSHOTS

echo "Configuring screenshots to save in Downloads"
defaults write com.apple.screencapture location ~/Downloads
killall SystemUIServer

# CHROME

echo "Configuring incognito mode"
defaults write com.google.chrome IncognitoModeAvailability -integer 1


# ==================================================================
# MANUAL
# ==================================================================

cat << EOF

Most importantly, my task list (Todoist) is the single source of truth linking to everything else. 

Most things are taken care of automatically with the set up script, but some manual items are needed:

- Sync iTerm2 settings with `com.googlecode.iterm2.plist` dotfile
- Text Message Forwarding (on, from iPhone)
- Remove all dock icons
- Add Todoist as only permanent item in dock
- Delete unused factory Applications
- Remove notification center widgets
- General
  - Highlight color (Nova cyan)
- Keyboard
  - For each keyboard
    - Modifier keys caps lock (escape)
  - Touch bar (app controls)
- Users
  - Add avatar
  - Login items (`RescueTime`)
- Audio & video
  - Video input: webcam camera
  - Audio input: mic via XLR interface
  - Audio output: DAC
- Desktop & Screen Saver
  - Add desktop background
- Finder
  - Favorites (`trevordmiller` only)
  - Show all filename extensions (on)
  - Show warning before changing an extension (off)
  - Correct spelling automatically (off)
  - Remove items from the Trash after 30 days (on)
  - Keep folders on top when sorting by name (on)
- Touch ID
  - Login (on)
  - Apple Pay (on)
- iCloud
  - disable everything except Calendar, Photos, Contacts, Keychain, and Find My Mac)
- Notification Center
  - Do Not Disturb
    - Scheduled (on, from 11pm-7am)
    - When display is sleeping (on)
    - When mirroring to TVs and projectors (on)
    - Allow repeated calls (on)
    - Sort order (recents by app)
- Display
  - Night Shift
    - Scheduled (from sunset to sunrise)
    - Full warmth
- Sound
  - Alert sound (glass)
  - Alert volume (full)
- Sound
  - Show volume in menu bar (on)
- Todoist
  - Show in menu bar (off)
  - Show badge in dock icon (off)
- Calendar
  - Add "Personal" and "Work" accounts
  - Time to leave (on)
  - Show shared calendar messages in notification center (off)
- Chrome
  - Set as default browser
  - Add "personal" and "work" profiles, signed in to the related google account
  - Extensions
    - Confirm install (1Password, Grammarly, Vimium, React DevTools, Apollo DevTools)
    - Vimium custom mappings
      - map <c-b> scrollFullPageUp
      - map <c-f> scrollFullPageDown
    - Sign in
    - Hide icons in Chrome menu
  - Safe search (on, locked)
- WakaTime
  - Add API key to `~/.wakatime.cfg`
- Screenflow
  - Enter licence
  - Remove recording countdown
  - Add audio driver for computer sound
- SwitchResX
  - Enter licence
  - Show only 1080p60 (HiDPI) and 720p60 (HiDPI) options
- Windows via Boot Camp Assistant
  - Official ISO file from Microsoft
  - 150gb partition
  - Skip key
  - Switch scroll direction
  - Change caps to escape
  - For each keyboard
    - Change caps lock to escape
  - Download Steam

Then, restart desktop.

# Mobile setup (iPhone)

- Turn hardware silent toggle switch on
- Settings
  - Sign in with Apple ID
  - Add Face ID
  - Set background pictures
  - Text message forwarding to desktop
  - Send as SMS when iMessage is unavailable
  - Don't store passwords in Safari
  - Restrictions (on), explicit (off), movies (PG-13), TV Shows (TV-14), explicit Language (off), websites (Limit Adult Content)
  - Cellular turn off large media apps
  - Do Not Disturb scheduled
  - Do Not Disturb automatically while driving
  - Night Shift scheduled with full warmth
  - Turn off keyboard auto capitalization and auto spelling correction
- Remove widgets
- Remove unused stock apps
- Download and configure 1Password
  - Add vault
  - Allow unlock with Face ID
  - Show in Safari share
- Dock has only Todoist
- Todoist
  - Turn off badge notifications for count
- Phone
- Messages
- Clock
  - Weekday alarm
  - Weekend alarm
- Calendar
  - Add "personal" and "work" accounts
  - Show shared calendar messages in notification center (off)
- Maps
- Safari
  - Google safe search
- Gospel Library
  - Sign in
- Feedly
  - Sign in 
- Anki
  - Disable badge notifications
- Edgar
- Spotify
  - Sign in
  - Download current playlist(s) offline
- background/ folder
  - 1Password
    - Already done ^
  - Contacts
    - Special sound/vibrate pattern for Amy
    - Emergency bypass call and text for Amy
  - Photos
  - Camera
  - Find iPhone
    - Turn on Send Last Location
  - Health
  - Wallet
    - Add debit card for Apple Pay
  - App Store
  - Settings
    - Already done ^

# Keyboard setup (Poker 3)

- Swap command and alt keys to match mac setup inside Mac and Windows

# Router setup

- [OpenDNS Family Shield](https://www.opendns.com/setupguide/?url=familyshield)

EOF
