#!/bin/bash
set -euo pipefail


# ==================================================================
# ROOT
# ==================================================================

cd ~
mkdir projects
cd projects


# ==================================================================
# SHELL SCRIPTS
# ==================================================================

git clone https://github.com/trevordmiller/shell-scripts.git


# ==================================================================
# DOTFILES
# ==================================================================

git clone https://github.com/trevordmiller/dotfiles.git
cd dotfiles
./index


# ==================================================================
# PACKAGES
# ==================================================================

cd ~

# HOMEBREW

echo "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Installing and configuring Homebrew packages"

homebrew_packages=(
  "bash"
  "tmux"
  "reattach-to-user-namespace"
  "vim"
  "git"
  "node"
  "n"
  "mas"
)
for homebrew_package in "${homebrew_packages[@]}"; do
  brew install "$homebrew_package"
done

echo "Making bash the default shell"
chsh -s /bin/bash

echo "Installing Vim plugin manager"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    
echo "Installing Vim plugins"
vim +PlugInstall +qall

echo "Making Vim history file directories"
mkdir ~/.vim/{backup_files,swap_files,undo_files}

echo "Upgrading to latest Node"
n latest

echo "Adding npm user"
npm adduser

# RUBY

echo "Installing and configuring Ruby gems"

ruby_gems=(
  "travis"
)
for ruby_gem in "${ruby_gems[@]}"; do
  gem install "$ruby_gem"
done

echo "Adding Travis user"
travis login


# ==================================================================
# APPS & FONTS
# ==================================================================

echo "Installing Homebrew cask packages"

brew tap caskroom/fonts

homebrew_cask_packages=(
  "hyper"
  "google-chrome"
  "1password"
  "rescuetime"
  "kap"
  "spotify"
  "font-fira-mono"
  "font-quicksand"
)
for homebrew_cask_package in "${homebrew_cask_packages[@]}"; do
  brew cask install "$homebrew_cask_package"
done

echo "Installing Mac App Store apps"

mac_app_store_apps=(
  "585829637" # Todoist
  "1055511498" # Day One
)
for mac_app_store_app in "${mac_app_store_apps[@]}"; do
  mas install "$mac_app_store_app"
done


# ==================================================================
# MACOS
# ==================================================================

# KEYBOARD

echo "Configuring key repeat"
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# HIDDEN FILES

echo "Configuring hidden files to show"
defaults write com.apple.finder AppleShowAllFiles YES
killall Finder

# MENU BAR

echo "Configuring menu bar to autohide"
defaults write NSGlobalDomain _HIHideMenuBar -bool true
killall Finder

# DOCK

echo "Configuring dock to autohide"
osascript <<EOD
  tell application "System Events"
    if (get autohide of dock preferences) is false then
      tell dock preferences to set autohide to not autohide
    end if
  end tell
EOD

# SCREENSHOTS

echo "Configuring screenshots to save in Downloads"
defaults write com.apple.screencapture location ~/Downloads
killall SystemUIServer

# CHROME

echo "Configuring incognito mode"
defaults write com.google.chrome IncognitoModeAvailability -integer 1


# ==================================================================
# MANUAL
# ==================================================================

cat << EOF

Most things are taken care of automatically with the set up script, but some manual items are needed:

- Text Message Forwarding (on, from iPhone)
- Remove all dock icons
- Delete unused factory Applications
- Remove notification center widgets
- General
  - Highlight color (Nova cyan)
- Keyboard
  - Modifier keys caps lock (escape)
  - Touch bar (app controls)
- Users
  - Add avatar
  - Login items (`RescueTime`, `Kap`)
- Desktop & Screen Saver
  - Add desktop background
- Finder
  - Favorites (`trevordmiller` only)
  - Show all filename extensions (on)
  - Show warning before changing an extension (off)
  - Correct spelling automatically (off)
  - Remove items from the Trash after 30 days (on)
  - Keep folders on top when sorting by name (on)
- Touch ID
  - Login (on)
  - Apple Pay (on)
- iCloud
  - disable everything except Calendar, Photos, Contacts, Keychain, and Find My Mac)
- Notification Center
  - Do Not Disturb
    - Scheduled (on, from 11pm-7am)
    - When display is sleeping (on)
    - When mirroring to TVs and projectors (on)
    - Allow repeated calls (on)
    - Sort order (recents by app)
- Display
  - Night Shift
    - Scheduled (from sunset to sunrise)
- Sound
  - Alert sound (glass)
  - Alert volume (full)
- Sound
  - Show volume in menu bar (on)
- Todoist
  - Show in menu bar (off)
  - Show badge in dock icon (off)
- Calendar
  - Add "Personal" and "Work" accounts
  - Start week on (Sunday)
  - Alerts (10 minutes before)
  - Time to leave (on)
  - Show shared calendar messages in notification center (off)
- Chrome
  - Set as default browser
  - Create "Personal" and "Work" users, signed in to the related google account
  - Extensions
    - Confirm install (1Password, Grammarly, React DevTools, Apollo DevTools)
    - Sign in
    - Hide icons in Chrome menu
  - Safe search (on, locked)
- WakaTime
  - Add API key to `~/.wakatime.cfg`
- Kap
  - Save to (`/Downloads`)
- Spotify
  - High quality streaming (on)
  - Show unavailable songs in playlists (on)
  - Show sponsored songs (off)
  - Show friends feed (off)
  - Auto play similar songs when your music ends (off)
  - Open Spotify automatically on login (off)

Then, restart desktop.

# Mobile setup

- Hardware
  - Silent toggle switch (on)
- Desktop
  - [iPhone as 2fa option](https://appleid.apple.com)
- `Applications` folder
  - Todoist
  - Calendar
    - Add "Personal" and "Work" accounts
  - Messages
  - Phone
  - Mail
  - Anki
    - Sync with AnkiWeb
  - Gospel Library
    - Sign in and sync notes/highlights
    - Download items (scriptures, past few conferences)
  - Feedly
  - Kindle
  - Day One
    - Day One enable sync (on)
  - Safari
    - AutoFill Names and Passwords (off)
    - Google safe search (on)
  - Clock
    - Bedtime (11pm - 7am)
  - Spotify
    - Download playlists
  - Maps
  - Lyft
  - 1Password
    - 1password accounts (tramy, work), touch ID (on), Watchtower (on)
  - Camera
  - Photos
    - iCloud Photo Library (on)
  - Google Photos
    - Upload size (original)
  - Contacts
    - Special sound/vibrate pattern for Amy
    - Emergency bypass call and text for Amy
  - Wallet
    - Add debit card to Apple Wallet for Apple Pay
  - Find iPhone
    - Store last known location (on)
  - Health
    - Medical ID (fill out)
  - App Store
  - Settings
    - Add multiple Touch ID fingers
    - Keyboard auto-Capitalization (off), auto-Correction (off)
    - Cellular (turn off large media apps)
    - Do Not Disturb scheduled (on, from 11pm-7am), allow calls from (Amy), repeated calls (on), silence (always)
    - Night Shift (scheduled, from sunset to sunrise)
    - Silence (always)
    - Restrictions (on), explicit (off), movies (PG-13), TV Shows (TV-14), explicit Language (off), websites (Limit Adult Content)
    - Auto-Brightness (on)
    - Wallpaper
    - User avatar
    - Text message forwarding (on)
    - Keep text messages (1 Year)
    - Text message read receipt (off)
    - Do Not Track (on)
- Delete unused apps

# Router setup

- [OpenDNS Family Shield](https://www.opendns.com/setupguide/?url=familyshield)

EOF
