#!/bin/bash
set -euo pipefail

# ==================================================================
# ROOT
# ==================================================================

cd ~
mkdir repos

# ==================================================================
# SHELL SCRIPTS
# ==================================================================

echo "Cloning shell scripts"
cd ~/repos
git clone https://github.com/trevordmiller/shell-scripts.git
cd ~

# ==================================================================
# DOTFILES
# ==================================================================

echo "Cloning dotfiles"
cd ~/repos
git clone https://github.com/trevordmiller/dotfiles.git
cd dotfiles
./index
cd ~

# ==================================================================
# PACKAGES
# ==================================================================

echo "Installing Homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Adding Homebrew taps"
homebrew_taps=(
	"universal-ctags/universal-ctags"
)
for homebrew_tap in "${homebrew_taps[@]}"; do
	brew tap "$homebrew_tap"
done

echo "Installing global Homebrew packages"
homebrew_packages=(
	"bash"
	"bash-completion"
	"shfmt"
	"the_silver_searcher"
	"tmux"
	"reattach-to-user-namespace"
	"fzf"
	"universal-ctags"
	"vim"
	"git"
	"node"
	"n"
	"mas"
)
for homebrew_package in "${homebrew_packages[@]}"; do
	brew install "$homebrew_package"
done

echo "Installing Vim plugin manager"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing Vim plugins"
vim +PlugInstall +qall

echo "Creating Vim history file directories"
mkdir ~/.vim/{backup_files,swap_files,undo_files}

echo "Upgrading node"
n lts

echo "Upgrading npm"
npm install npm -g

echo "Adding npm user"
npm adduser

echo "Installing global node packages"
node_packages=(
	"eslint"
	"prettier"
)
for node_package in "${node_packages[@]}"; do
	npm install -g "$node_package"
done

# ==================================================================
# APPS / FONTS
# ==================================================================

echo "Installing Homebrew cask apps and fonts"
brew tap caskroom/fonts
homebrew_cask_packages=(
	"font-fira-mono"
	"iterm2"
	"1password"
	"rescuetime"
	"google-chrome"
	"anki"
	"spotify"
)
for homebrew_cask_package in "${homebrew_cask_packages[@]}"; do
	brew cask install "$homebrew_cask_package"
done

echo "Installing Mac App Store apps"
mac_app_store_apps=(
	"585829637" # Todoist
	"1055511498" # Day One
)
for mac_app_store_app in "${mac_app_store_apps[@]}"; do
	mas install "$mac_app_store_app"
done

# ==================================================================
# MACOS
# ==================================================================

# KEYBOARD

echo "Configuring key repeat"
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# HIDDEN FILES

echo "Configuring hidden files to show"
defaults write com.apple.finder AppleShowAllFiles YES
killall Finder

# MENU BAR

echo "Configuring menu bar to autohide"
defaults write NSGlobalDomain _HIHideMenuBar -bool true
killall Finder

# DOCK

echo "Configuring dock to autohide"
osascript <<EOD
  tell application "System Events"
    if (get autohide of dock preferences) is false then
      tell dock preferences to set autohide to not autohide
    end if
  end tell
EOD

# SCREENSHOTS

echo "Configuring screenshots to save in Downloads"
defaults write com.apple.screencapture location ~/Downloads
killall SystemUIServer

# BLUETOOTH AUDIO

echo "Configuring highest quality bluetooth audio"
sudo defaults write bluetoothaudiod "Enable AAC codec" -bool true

# CHROME

echo "Configuring incognito mode"
defaults write com.google.chrome IncognitoModeAvailability -integer 1

# ==================================================================
# MANUAL
# ==================================================================

cat <<EOF

Most importantly, my task list (Todoist) is the single source of truth linking to everything else. 

Most things are taken care of automatically with the set up script, but some manual items are needed:

- Install my ethernet adapter drivers from http://www.asix.com.tw/FrootAttach/driver/AX88179_178A_Macintosh_Driver_Installer_v2.9.0_20171011.zip
- Sync iTerm2 settings with com.googlecode.iterm2.plist dotfile
- Text Message Forwarding (on, from iPhone)
- Remove all dock icons other than Todoist
- Delete unused factory Applications
- Remove notification center widgets
- Keyboard
  - For each keyboard
    - Modifier keys caps lock (escape)
  - Touch bar (app controls)
- Display
  - For 4k monitors, scaled for larger text (to look like double the resolution)
  - Night Shift
    - Scheduled (from sunset to sunrise)
    - Full warmth
- General
  - Appearance (Graphite)
  - Highlight color (Nova cyan)
- Users
  - Add avatar
  - Login items (RescueTime)
- Audio & video
  - Audio input: audio interface
  - Audio output: audio interface
  - Video input: webcam camera
- Desktop & Screen Saver
  - Add temple background picture
- Finder
  - Favorites (trevordmiller) only)
  - Show all filename extensions (on)
  - Show warning before changing an extension (off)
  - Correct spelling automatically (off)
  - Remove items from the Trash after 30 days (on)
  - Keep folders on top when sorting by name (on)
- Face ID
  - Login (on)
  - Apple Pay (on)
- iCloud
  - Enable everything
- Family Sharing
  - Enable everything
- Notification Center
  - Do Not Disturb
    - Scheduled (on, from 11pm-7am)
    - When display is sleeping (on)
    - When mirroring to TVs and projectors (on)
    - Allow repeated calls (on)
    - Sort order (recents by app)
  - Turn off notifications for all apps that have email notifications
- Sound
  - Alert sound (glass)
  - Alert volume (full)
- Sound
  - Show volume in menu bar (on)
- Todoist
  - Show in menu bar (off)
  - Show badge in dock icon (off)
- Calendar
  - Time to leave (on)
  - Show shared calendar messages in notification center (off)
- Chrome
  - Set as default browser
  - Add "personal" profile, signed in to personal google account
    - Safe search (on, locked)
    - Extensions
      - 1Password
      - Vimium
        - Vimium custom mappings
          - map <c-b> scrollFullPageUp
          - map <c-f> scrollFullPageDown
      - React DevTools
      - Hide icons in Chrome menu
- WakaTime
  - Add API key to "~/.wakatime.cfg"
- Spotify
  - Sign in
  - Highest quality of streaming and downloads
  - Download playlists offline
  - Hide unplayable songs (off)
  - Autoplay (off)
- Windows via Boot Camp Assistant
  - Official ISO file from Microsoft
    - 64 bit
    - English
  - 150gb partition
  - Version: Windows 10 Home
  - Skip registration key
  - Enhance pointer precision (off)
  - Download Blizzard.net app
  - 800 mouse DPI
  - Overwatch
    - Mouse sensitivity (5.0 for 4000 eDPI)
    - Music Volume (off)
    - Allied health bars (on)
  - Set Startup Disk to macOS

Then, restart desktop.

# Mobile (iPhone)

- Turn hardware silent toggle switch on
- Settings
  - Sign in with Apple ID
  - Add Face ID
  - Add Christ background pictures
  - Text message forwarding to desktop
  - Send as SMS when iMessage is unavailable
  - Don't store passwords in Safari
  - Restrictions (on), explicit (off), movies (PG-13), TV Shows (TV-14), explicit Language (off), websites (Limit Adult Content)
  - Cellular turn off large media apps
  - Do Not Disturb scheduled
  - Do Not Disturb automatically while driving
  - Night Shift scheduled with full warmth
  - Turn off keyboard auto capitalization and auto spelling correction
  - Turn off notifications for all apps that aren't critical for mobile / have email notifications
- Remove widgets
- Remove unused stock apps
- Download and configure 1Password
  - Add vault
  - Allow unlock with Face ID
  - Show in Safari share
- Homescreen
  - Todoist
    - The only app in the dock
  - Calendar
  - Messages
  - Phone
  - Safari
    - Google safe search
    - Block pop-ups (on)
    - Prevent Cross-Site Tracking (on)
    - Ask websites not to track me (on)
    - Fraudulent website warning (on)
    - Check for Apple Pay (on)
  - Gospel Library
    - Sign in
  - LDS Tools
    - Sign in
    - Use Face ID
    - Enable caller ID in iPhone Settings Call Blocking & Identification
  - Camera
  - Spotify
    - Sign in
    - Highest quality of streaming and downloads
    - Download playlists offline
    - Hide unplayable songs (off)
    - Autoplay (off)
  - Clock
    - Weekday alarm
    - Weekend alarm
  - Maps
  - Settings
    - Already done ^
- background/ folder on second screen
  - 1Password
    - Already done ^
  - iSmartAlarm
    - Sign in
  - Nest
    - Connect Nest Protect and Thermostat
    - Add my phone to emergency contact
    - Home away/assist (off)
    - Auto-schedule (off)
    - Fan schedule (15 minutes every hour, 9am-9pm)
  - Contacts
    - Special sound/vibrate pattern for Amy
    - Emergency bypass call and text for Amy
    - Emergency bypass call and text for iSmartAlarm
    - Emergency bypass call and text for Nest
  - Photos
  - Google Photos
    - Back up & sync (on)
    - Original quality (on)
    - Location history (on)
  - Find iPhone
    - Turn on Send Last Location
  - Health
    - Set up profile and medical ID
  - Wallet
    - Add debit card for Apple Pay
  - App Store
- Per phone number
  - Sign up for National Do Not Call Registry at https://www.donotcall.gov

# TV (Apple TV)

- Homescreen
  - TV
    - The Office
    - Psych
    - Speechless
    - The Good Place
    - Modern Family
    - Trial & Error
    - Brooklyn Nine-Nine
    - Monk
    - Chuck
    - Parks and Recreation
    - Big Bang Theory
    - Superstore
    - AFV
    - Timeless
    - This Is Us
  - YouTube
    - Sign in
  - Twitchy
    - Overwatch League
  - Photos
  - background/ folder
    - Prime Video
    - Hulu
    - Netflix
    - App Store
    - Settings
- Restrictions (on), explicit (off), movies (PG-13), TV Shows (TV-14), explicit Language (off), websites (Limit Adult Content)

# Router

- OpenDNS Family Shield
  - Open router preferences at http://192.168.0.1
  - Select Advanced Setup
  - Select WAN settings
  - Change DNS type to static DNS
  - Add FamilyShield OpenDNS server addresses as DNS server settings and save
    - Primary DNS: 208.67.222.123
    - Secondary DNS: 208.67.220.123
  - Repeat for IPv6 WAN settings
  - Check it is working at https://welcome.opendns.com and http://www.internetbadguys.com

# Thermostat (Nest)

- Set temperature, don't change/track automatically

# Smoke / Carbon Monoxide (Nest Protect)

- Monthly self-check
- Call + text air and battery alerts

EOF
