#!/bin/bash
set -euo pipefail

AUTHOR="trevordmiller"

if [ `date +%w` == 1 ] ; then
  LIMIT="3 days"
else
  LIMIT="yesterday"
fi

git log --all --author="$AUTHOR" --after="$LIMIT" --decorate --graph
