#!/bin/bash
set -euo pipefail

AUTHOR="trevordmiller"

if [ $(date +%w) == 1 ]; then
	LIMIT="3 days ago"
else
	LIMIT="yesterday"
fi

git fetch

clear

echo "Commits:"
git log --all --author="$AUTHOR" --after="$LIMIT" --decorate --graph

echo "Merged:"
git log --merges --author="$AUTHOR" --after="$LIMIT"

echo "In review:"
git branch --no-merged master

echo "Next:"
git status
