#!/bin/bash
set -euo pipefail

AUTHOR="trevordmiller"

if [ `date +%w` == 1 ] ; then
  LIMIT="3 days ago"
else
  LIMIT="yesterday"
fi

git fetch

echo "MERGED:"
git log --merges --author="$AUTHOR" --after="$LIMIT"

echo "UNMERGED:"
git branch --no-merged master

echo "DOING:"
git status
