#!/bin/bash
set -euo pipefail

osascript <<EOD
tell application "iTerm"
  make new terminal
  tell the current terminal
    activate current session
    launch session "Default Session"
    tell the last session
      write text "snout"
    end tell
  end tell
end tell
EOD

open -a "Todoist"
open -a "Trello"
open -a "Slack"
open -a "Calendar"
open -a "Spotify"
open -a "Google Chrome" --args --profile-directory="Profile 1"
open "http://localhost:4000"
