#!/bin/bash
set -euo pipefail

open "/Applications/Todoist.app"
open "/Applications/Hyper.app"
fullscreen
open "/Applications/Spotify.app"
open -a "/Applications/Google Chrome.app" --args --profile-directory="Default"
