#!/bin/bash
set -euo pipefail

# ==================================================================
# APPS
# ==================================================================

apps=(
	"Alacritty"
	"Microsoft Outlook"
	"Microsoft Teams"
)

for app in "${apps[@]}"; do
	open -a "$app"
done

# ==================================================================
# WEBSITES
# ==================================================================

websites=(
	"https://ankiweb.net"
	"https://feedly.com"
	"https://feedly.com/i/saved"
	"https://code.ldschurch.org/git/dashboard"
	"https://code.ldschurch.org/jira/secure/RapidBoard.jspa?rapidView=2279&quickFilter=12808"
)

open -a "Safari"
for website in "${websites[@]}"; do
	open "$website"
done
