#!/bin/bash
set -euo pipefail

websites=(
  "https://open.spotify.com"
  "https://roederstudios.slack.com"
  "https://trello.com/b/55pvbyFV/ropig-dev?menu=filter&filter=@trevormiller14"
)

open -a "Google Chrome" --args --profile-directory="Profile 1"
for website in "${websites[@]}"; do
  open "$website"
done

native_apps=(
  "Todoist"
  "Safari"
  "Firefox"
)

for native_app in "${native_apps[@]}"; do
  open -a "$native_app"
done
