#!/bin/bash
set -euo pipefail

# ==================================================================
# APPS
# ==================================================================

apps=(
	"Todoist"
	"Microsoft Outlook"
	"Microsoft Teams"
	"iTerm"
)

for app in "${apps[@]}"; do
	open -a "$app"
done

# ==================================================================
# WEBSITES
# ==================================================================

websites=(
	"https://code.ldschurch.org/git/dashboard"
	"https://ankiweb.net"
	"https://feedly.com"
	"https://feedly.com/i/saved"
)

open -a "Google Chrome"
for website in "${websites[@]}"; do
	open "$website"
done
