#!/bin/bash
set -euo pipefail

native_apps=(
  "Todoist"
  "Spotify"
)

for native_app in "${native_apps[@]}"; do
  open -a "$native_app"
done

open -a "Google Chrome" --args --profile-directory="Profile 3"
