#!/bin/bash
set -euo pipefail

websites=(
  "https://todoist.com/app"
  "https://open.spotify.com"
  "https://github.com/issues?q=is%3Aopen+user%3Atrevordmiller"
)

open -a "Google Chrome" --args --profile-directory="Profile 3"
for website in "${websites[@]}"; do
  open "$website"
done
