#!/bin/bash
set -euo pipefail

native_apps=(
  "Todoist"
  "Messages"
  "Calendar"
  "Mail"
  "Photos"
  "Day One"
  "Anki"
  "Spotify"
)

for native_app in "${native_apps[@]}"; do
  open -a "$native_app"
done

websites=(
  "https://lifesum.com/account"
  "https://www.rescuetime.com/dashboard"
  "https://wakatime.com/dashboard"
  "https://webaccess.americafirst.com/AFCU/Accounts/PMMActivity.aspx?index=3"
  "https://app.youneedabudget.com"
  "https://www.facebook.com"
  "https://discordapp.com/channels/@me"
  "https://www.reddit.com"
  "https://www.youtube.com/playlist?list=WL"
  "https://feedly.com"
  "https://read.amazon.com/notebook"
  "https://app.meetedgar.com"
  "https://www.reddit.com/user/trevordmiller"
  "https://analytics.twitter.com"
  "https://www.facebook.com/trevordmillercom/insights"
  "https://analytics.google.com"
  "https://us3.admin.mailchimp.com/reports/#t:campaigns-list"
  "https://trevordmiller.teachable.com/admin"
  "https://instructor.egghead.io"
)

open -a "Google Chrome" --args --profile-directory="Profile 3"
for website in "${websites[@]}"; do
  open "$website"
done
