#!/bin/bash
set -euo pipefail

websites=(
  "https://www.icloud.com/#calendar"
  "https://www.icloud.com/#mail"
  "https://webaccess.americafirst.com/AFCU/Accounts/PMMActivity.aspx?index=3"
  "https://app.youneedabudget.com"
  "https://www.facebook.com"
  "https://www.rescuetime.com/dashboard"
  "https://wakatime.com/dashboard"
  "https://feedly.com"
  "https://app.meetedgar.com"
  "https://www.reddit.com/user/trevordmiller"
  "https://analytics.twitter.com"
  "https://www.facebook.com/trevordmillercom/insights"
  "https://analytics.google.com"
  "https://us3.admin.mailchimp.com/reports/#t:campaigns-list"
  "https://trevordmiller.teachable.com/admin"
  "https://instructor.egghead.io"
)

open -a "Google Chrome" --args --profile-directory="Profile 3"
for website in "${websites[@]}"; do
  open "$website"
done

native_apps=(
  "Todoist"
  "Messages"
  "Photos"
  "Day One"
  "Anki"
)

for native_app in "${native_apps[@]}"; do
  open -a "$native_app"
done

websites=(
  "https://mail.google.com"
  "http://smashvods.com/roa"
  "https://app.meetedgar.com"
  "https://www.reddit.com/user/roatutorials"
  "https://analytics.twitter.com"
  "https://www.facebook.com/RoA-Tutorials-1269504136488638/insights"
  "https://www.patreon.com"
)

open -a "Google Chrome" --args --profile-directory="Profile 5"
for website in "${websites[@]}"; do
  open "$website"
done
