#!/bin/bash
set -euo pipefail

websites=(
  "https://calendar.google.com"
  "https://mail.google.com"
  "https://roederstudios.slack.com"
  "https://trello.com/b/55pvbyFV/ropig-dev"
  "https://app.bugsnag.com/lkr/ropig-front-end"
  "https://app.asana.com/0/212309631908144"
)

open -a "Google Chrome" --args --profile-directory="Profile 1"
for website in "${websites[@]}"; do
  open "$website"
done

native_apps=(
  "Todoist"
)

for native_app in "${native_apps[@]}"; do
  open -a "$native_app"
done
