#!/bin/bash
set -euo pipefail

websites=(
  "https://mail.google.com"
)

open -a "Google Chrome" --args --profile-directory="Profile 1"
for website in "${websites[@]}"; do
  open "$website"
done

native_apps=(
  "Todoist"
  "Trello"
  "Slack"
  "Calendar"
)

for native_app in "${native_apps[@]}"; do
  open -a "$native_app"
done
