#!/bin/bash
set -euo pipefail

websites=(
  "https://www.icloud.com/#calendar"
  "https://www.icloud.com/#mail"
  "https://app.youneedabudget.com"
  "https://www.facebook.com"
  "https://feedly.com"
  "https://app.meetedgar.com"
  "https://www.facebook.com/trevordmillercom/insights"
  "https://analytics.twitter.com"
  "https://analytics.google.com"
  "https://us3.admin.mailchimp.com/reports/#t:campaigns-list"
  "https://trevordmiller.teachable.com/admin"
  "https://instructor.egghead.io"
)

open -a "Google Chrome" --args --profile-directory="Profile 3"
for website in "${websites[@]}"; do
  open "$website"
done

native_apps=(
  "Todoist"
  "Messages"
  "Photos"
  "Day One"
  "Anki"
)

for native_app in "${native_apps[@]}"; do
  open -a "$native_app"
done
