#!/bin/bash
set -euo pipefail

cd ~
tmux new-session -d -s trevordmiller-website
tmux-window "trevordmiller-website" "repos/trevordmiller-website" 2 "npm run dev"
tmux kill-window -t 0
tmux select-window -t 1
tmux attach-session -d 
