#!/bin/bash
set -euo pipefail


# ==================================================================
# APPS
# ==================================================================

apps=(
  "Todoist"
  "iTerm"
  "Mail"
  "Spotify"
)

for app in "${apps[@]}"; do
  open -a "$app"
done

open -a "Google Chrome" --args --profile-directory="Profile 3"


# ==================================================================
# TERMINAL WORKFLOW
# ==================================================================

cd ~
DEFAULT_DIRECTORY="repos/trevordmiller-website"
tmux new-window -c "$DEFAULT_DIRECTORY"
tmux rename-window "trevordmiller-website"
tmux split-window -c "$DEFAULT_DIRECTORY"
tmux split-window -c "$DEFAULT_DIRECTORY"
tmux send-keys -t 0 C-z "vim -c 'E'" Enter
tmux send-keys -t 1 C-z "npm run dev" Enter
tmux send-keys -t 2 C-z "git status" Enter
tmux select-layout main-horizontal
tmux resize-pane -t:.0 -y $(expr $(tmux display -p '#{window_height}') / 3 \* 2)
tmux select-pane -t 0
