#!/bin/bash
set -euo pipefail

# ==================================================================
# APPS
# ==================================================================

apps=(
	"Todoist"
	"Calendar"
	"Messages"
	"Mail"
	"Photos"
	"Day One"
	"Anki"
)

for app in "${apps[@]}"; do
	open -a "$app"
done

# ==================================================================
# WEBSITES
# ==================================================================

websites=(
	"https://app.youneedabudget.com"
	"https://feedly.com"
	"https://feedly.com/i/saved"
)

DAYOFWEEK=$(date +"%u")
if [ "${DAYOFWEEK}" -eq 1 ]; then
	websites+=('https://www.facebook.com')
	websites+=('https://twitter.com')
	websites+=('https://utahjavascript.slack.com')
fi

open -a "Google Chrome" --args --profile-directory="Profile 3"
for website in "${websites[@]}"; do
	open "$website"
done
