#!/bin/bash
set -euo pipefail

# ==================================================================
# APPS
# ==================================================================

apps=(
	"Todoist"
	"Calendar"
	"Messages"
	"Mail"
	"Photos"
	"Day One"
)

for app in "${apps[@]}"; do
	open -a "$app"
done

# ==================================================================
# WEBSITES
# ==================================================================

websites=(
	"https://my.1password.com/vaults/v6npp3fcckviz7tcpxfgtgvbfm/watchtower"
	"https://my.1password.com/vaults/r77xxemjsuaqm5nolgy2z4q2ea/watchtower"
	"https://app.youneedabudget.com"
)

open -a "Google Chrome" --args --profile-directory="Profile 3"
for website in "${websites[@]}"; do
	open "$website"
done
