#!/bin/bash
set -euo pipefail

# ==================================================================
# PACKAGES
# ==================================================================

# HOMEBREW

echo "Upgrading Homebrew packages"
brew update
brew upgrade
brew doctor

echo "Upgrading Vim plugins"
vim +PlugUpgrade +PlugUpdate +PlugClean +qall

echo "Upgrading npm"
npm i npm

# ==================================================================
# MAC APP STORE
# ==================================================================

echo "Upgrading Mac App Store apps"
mas upgrade

# ==================================================================
# MACOS
# ==================================================================

echo "Upgrading macOS"
sudo softwareupdate -ia
