#!/bin/bash
set -euo pipefail

echo "Upgrading global Homebrew packages"
brew update
brew upgrade

echo "Upgrading Vim plugins"
vim +PlugUpgrade +PlugUpdate +PlugClean +qall

echo "Upgrading Node / npm for JavaScript projects"
. "/usr/local/opt/nvm/nvm.sh"
nvm install --lts
nvm use --lts

echo "Upgrading OS"
sudo softwareupdate -ia
