#!/bin/sh

# -----------------------------------------------------------------
# Operating system (macOS)
# -----------------------------------------------------------------

echo "Upgrading operating system"
sudo softwareupdate -ia

echo "Upgrading package manager"
brew update

echo "Upgrading apps"
brew cask upgrade 1password

# -----------------------------------------------------------------
# Environment (Unix)
# -----------------------------------------------------------------

echo "Upgrading shell"
brew upgrade zsh

echo "Setting default shell"
sudo sh -c "echo $(which zsh) >> /etc/shells"
chsh -s $(which zsh)

# -----------------------------------------------------------------
# Editor (Vim)
# -----------------------------------------------------------------

echo "Upgrading editor"
brew upgrade vim

echo "Upgrading editor plugin manager"
vim +PlugUpgrade +qall

echo "Upgrading editor plugins"
vim +PlugUpdate +PlugClean +qall

# -----------------------------------------------------------------
# Version control (Git)
# -----------------------------------------------------------------

echo "Upgrading version control"
brew upgrade git

# -----------------------------------------------------------------
# Application programming (JavaScript)
# -----------------------------------------------------------------

echo "Upgrading application programming toolchain"
. ~/.nvm/nvm.sh
nvm install --lts
nvm use --lts

# -----------------------------------------------------------------
# Systems programming (Rust)
# -----------------------------------------------------------------

echo "Upgrading systems programming toolchain"
rustup update

# -----------------------------------------------------------------

echo "Finished"
