#!/bin/bash
set -euo pipefail

# ==================================================================
# APPS
# ==================================================================

apps=(
	"Todoist"
	"Calendar"
	"Mail"
	"Microsoft Teams"
	"iTerm"
	"Spotify"
)

for app in "${apps[@]}"; do
	open -a "$app"
done

# ==================================================================
# WEBSITES
# ==================================================================

websites=(
	"https://docs.google.com/document/d/1_VVsWcN0e5eoFiRK1U_vODdViSHNnRO6dE1y5EZ76Xw"
)

open -a "Google Chrome"
for website in "${websites[@]}"; do
	open "$website"
done
