#!/bin/bash
set -euo pipefail

# ==================================================================
# APPS
# ==================================================================

apps=(
	"Todoist"
	"Calendar"
	"Mail"
	"Microsoft Teams"
	"iTerm"
	"Spotify"
)

for app in "${apps[@]}"; do
	open -a "$app"
done
